#!/usr/bin/env python3
"""Rewrite a Google-Fonts CSS file to point at local copies of the referenced woff2 files."""
import hashlib
import os
import re
import sys
import urllib.request

src_css, out_dir, css_out = sys.argv[1], sys.argv[2], sys.argv[3]
with open(src_css, "r", encoding="utf-8") as f:
    css = f.read()


def local_name(url: str) -> str:
    """Stable filename for a remote font URL: short sha1 + .woff2."""
    digest = hashlib.sha1(url.encode()).hexdigest()[:16]
    return f"{digest}.woff2"


def ensure_downloaded(url: str) -> str:
    name = local_name(url)
    dst = os.path.join(out_dir, name)
    if not os.path.exists(dst):
        print(f"  \u2193 {name}  ({url.rsplit('/', 1)[-1]})")
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req) as r, open(dst, "wb") as out:
            out.write(r.read())
    return name


def rewrite(match: "re.Match[str]") -> str:
    return f"url(fonts/{ensure_downloaded(match.group(1))})"


css = re.sub(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", rewrite, css)

header = "/* Generated by tools/fetch-fonts.sh \u2014 do not edit by hand. */\n"
with open(css_out, "w", encoding="utf-8") as f:
    f.write(header + css)
print(f"Wrote {css_out}")
